---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.1
  sha1: e876542ad3f2d4cee842b3bf1bfe4d435aaa85cd
- name: bosh-aws-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=53
  sha1: 3a5988bd2b6e951995fe030c75b07c5b922e2d59

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3262
    sha1: f04361747243dadc6e13ce74f5044b46931fb00a
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk: {size: 25_000, type: gp2}
    availability_zone: us-east-1a # <--- Replace with Availability Zone

disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties: {type: gp2}

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [10.0.0.2]
    cloud_properties: {subnet: subnet-1c90ef6b} # <--- Replace with Subnet ID
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: powerdns, release: bosh}   # dynamic networking requirement
  - {name: aws_cpi, release: bosh-aws-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [10.0.0.6]
    default: [dns, gateway]
  - name: public
    static_ips: [52.70.98.70] # <--- Replace with Elastic IP

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    dns:
      address: 10.0.0.6
      recursor: 8.8.8.8   # Concourse requires recursion
      db:
        user: postgres
        password: postgres-password

    registry:
      address: 10.0.0.6
      host: 10.0.0.6
      db: *db
      http: {user: admin, password: ADMIN_PASSWORD, port: 25777} # <--- Replace with admin's password
      username: admin
      password: ADMIN_PASSWORD # <--- Replace with admin's password
      port: 25777

    blobstore:
      address: 10.0.0.6
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: BOSH
      db: *db
      cpi_job: aws_cpi
      max_threads: 20
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: ADMIN_PASSWORD} # <--- Replace with admin's password
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true

    aws: &aws
      access_key_id: AKIAxxxxxxxxxxxxxxxx # <--- Replace with AWS Access Key ID
      secret_access_key: 0+B1XW6VVEYxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # <--- Replace with AWS Secret Key
      default_key_name: aws_nono
      # the Security Group MUST have the VPC ID of your VPC (e.g. 'vpc-e4250881')
      default_security_groups: [bosh]
      region: us-east-1 # <--- Replace with Region

    agent: {mbus: "nats://nats:nats-password@10.0.0.6:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: 52.70.98.70 # <--- Replace with your Elastic IP address
    port: 22
    user: vcap
    private_key: ../../.ssh/aws_nono.pem # Path relative to this manifest file

  mbus: "https://mbus:MBUS_PASSWORD@52.70.98.70:6868" # <--- Replace with Elastic IP

  properties:
    aws: *aws
    agent: {mbus: "https://mbus:MBUS_PASSWORD@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
